version: '3.8'

services:
  postgres:
    container_name: postgres-dev
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-anyEmail}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres:

networks:
  postgres:
